### ISSUE TITLE
Missing 'requests' module in Assets\lib

### ISSUE THREAD

**Issue by Snowyamur** [nobbyfix/AzurLaneTools#1]
Whenever I run `obb_import.py` using a file path that leads to an obb archive, I keep getting the error below in my terminal:

```
$ python obb_import.py -f C:\Users\snowy\Downloads\AzurLaneTools-master\Assets\main.60009.com.YoStarEN.AzurLane
Traceback (most recent call last):
  File "C:\Users\snowy\Downloads\AzurLaneTools-master\Assets\obb_import.py", line 7, in <module>
    from lib import versioncontrol, updater, config
  File "C:\Users\snowy\Downloads\AzurLaneTools-master\Assets\lib\updater.py", line 6, in <module>
    from . import downloader, versioncontrol
  File "C:\Users\snowy\Downloads\AzurLaneTools-master\Assets\lib\downloader.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

I ran this through Git Bash, so I'm not sure if this error is due to an issue terminal-side, or I'm actually missing a **'requests'** module in the files I downloaded from here.

**Comment by Snowyamur** [comment]
Discussed on Discord - resolved
